config/routes.rb
Punaise::Application.routes.draw do
  resources :currencies

  resources :boards

  resources :comments

  resources :puns

  resources :homes

  resources :states

  resources :countries

  devise_for :users

  resources :categories

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end
  
  resources :users

resources :puns, :only => [:index, :show] do
  resources :likes, :only => [:create, :destroy]
end

  get "users/:id/board" => "users#board"
  

  match '/:id/toggle_like', to: 'puns#toggle_like', as: 'toggle_like'
  match '/:id/toggle_follow', to: 'boards#toggle_follow', as: 'toggle_follow'

  root :to => 'homes#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :cover_id, :name, :description, :user_id, :slug

  acts_as_followable


  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user

  has_many :puns
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :approved, :content, :pun_id, :user_id

  belongs_to :user
  belongs_to :pun
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :continent_id, :flag, :name, :slug
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :is_enabled, :name, :symbol

  has_many :puns
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/pun.rb
class Pun < ActiveRecord::Base
  attr_accessible :board_id, :category_id, :image, :remote_image_url, :slug, :link, :description, :is_deleted, :original_board_id, :original_punaise_id, :original_user_id, :user_id, :price, :is_product, :currency_id, :websource

  extend FriendlyId
  friendly_id :description, use: :slugged

  acts_as_likeable

  mount_uploader :image, ImageUploader

  has_many :comments

  belongs_to :user
  belongs_to :board
  belongs_to :currency
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :country_id, :is_admin, :username, :slug, :state_id

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :username, use: :slugged

  acts_as_liker
  acts_as_follower
  acts_as_followable

  has_many :puns

  has_many :comments
  
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/puns_helper.rb
module PunsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_enabled %><br />
    <%= f.check_box :is_enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Is enabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.name %></td>
    <td><%= currency.is_enabled %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @currency.name %>
</p>

<p>
  <b>Is enabled:</b>
  <%= @currency.is_enabled %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>