config/routes.rb
Punaise::Application.routes.draw do
  resources :currencies

  resources :boards

  resources :comments

  resources :puns

  resources :homes

  resources :states

  resources :countries

  devise_for :users

  resources :categories

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end
  
  resources :users

resources :puns, :only => [:index, :show] do
  resources :likes, :only => [:create, :destroy]
end

  get "users/:id/board" => "users#board"
  

  match '/:id/toggle_like', to: 'puns#toggle_like', as: 'toggle_like'
  match '/:id/toggle_follow', to: 'boards#toggle_follow', as: 'toggle_follow'

  root :to => 'homes#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :cover_id, :name, :description, :user_id, :slug

  acts_as_followable


  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user

  has_many :puns
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :approved, :content, :pun_id, :user_id

  belongs_to :user
  belongs_to :pun
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :continent_id, :flag, :name, :slug
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :is_enabled, :name, :symbol

  has_many :puns
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/pun.rb
class Pun < ActiveRecord::Base
  attr_accessible :board_id, :category_id, :image, :remote_image_url, :slug, :link, :description, :is_deleted, :original_board_id, :original_punaise_id, :original_user_id, :user_id, :price, :is_product, :currency_id, :websource

  extend FriendlyId
  friendly_id :description, use: :slugged

  acts_as_likeable

  mount_uploader :image, ImageUploader

  has_many :comments

  belongs_to :user
  belongs_to :board
  belongs_to :currency
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :country_id, :is_admin, :username, :slug, :state_id

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :username, use: :slugged

  acts_as_liker
  acts_as_follower
  acts_as_followable

  has_many :puns

  has_many :comments
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :follow, :update, :destroy, :edit]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def board
    @user = User.find(params[:id])
    @boards = Board.where("user_id = ?", @user.id)

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end


  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def follow
    @user = User.find(params[:id])
    
    render :text => params.to_yaml
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/puns_helper.rb
module PunsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br />
    <%= f.number_field :country_id %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.number_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br />
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_like.js.erb
alert("hello");

app/views/users/_user_boards_list.html.erb
<div id="userboardslist">
	<% if user_signed_in? %>
	<% if (@user.id == current_user.id) %>
	<a href="<%= new_board_path() %>"><div class="newboard">
		<div class="addboard">
			
		</div>
		<div class="addboardtext">
			add a board
		</div>
	</div></a>
	<% end %>
	<% end %>
	<% Board.all.each do |board|  %>
      
	<div class="board">
		<div class="title">
			<%= link_to (board.name), board_path(board) %>
		</div>
		<div class="maincover">
			<% Pun.where("board_id = ?", board.id).first(1).each do |boardmainthumb| %>
	            <%= image_tag boardmainthumb.image_url(:userboardthumb).to_s %>
	        <% end %>
		</div>
		<div class="tinycovers">

			<% Pun.where("board_id = ?", board.id).last(4).each do |boardtinythumb| %>
				<div class="tinycover">
		            <%= image_tag boardtinythumb.image_url(:userboardtinythumb).to_s %>
				</div>
	        <% end %>
		</div>
		<div class="edit"><a href="">Modifier</a></div>
	</div>
	<% end %>	
</div>


</div>

app/views/users/_user_puns_list.html.erb
<div id="userpunslist">
    
    <div id="tiles">
        <% Pun.where("user_id = ?", @user.id).each do |pun| %>




      <li class="tile">

                <!-- La Punaise Elle meme -->
                <div class="lapunaise">

                  <%= link_to (image_tag pun.image_url(:grid).to_s), pun_path(pun) %>

                  <div id="pun-like-links">
                    <div class="top-link" id="punscount-<%= pun.id %>"><a href="#modal-<%= pun.id %>" rel="modal:open"><%= Pun.where("original_punaise_id = ?", pun.original_punaise_id).count + 1 %> <%= image_tag "icon/punaise2.png" %></a></div>
                    <div class="top-link" id="likescount-<%= pun.id %>"> <%= link_to pun.likers(User).count.to_s, toggle_like_path(pun), :remote => true %><%= link_to (image_tag "icon/love2.png"), toggle_like_path(pun), :remote => true %></div>
                  </div>

                </div>

                <!-- La description -->
                <% unless pun.description.nil? %>
                <div class="description">
                  <%= pun.description %>
                </div>
                <% end %>

                <ul class="pundatas">
                  <li class="pundata" %>
                    <div class="thumb">
                      <%= image_tag pun.user.avatar_url(:pundatathumb).to_s %>
                    </div>

                    <div class="data">
                      <div class="by">
                        par
                      </div>
                      <div class="user">
                        <%= link_to pun.user.username, user_path(pun.user) %>
                      </div>
                    </div>
                  </li>
                  

                  <!-- PUNNED ON -->
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.board_id).first(1).each do |boardthumb| %>
                        <%= link_to (image_tag boardthumb.image_url(:boardthumb).to_s), board_path(boardthumb.board) %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Clouée sur
                      </div>
                      <div class="board">

                        <%= link_to (pun.board.name), board_path(pun.board) %>


                      </div>
                    </div>

                  </li>

                  

                  <!-- ORIGINALLY PUNNED ON -->
                  <% unless pun.original_board_id.nil? %>
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.original_board_id).first(1).each do |boardthumb| %>
                        <%= link_to (image_tag boardthumb.image_url(:boardthumb).to_s), board_path(boardthumb.board) %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Originellement sur
                      </div>
                      <div class="board">
                        <% Board.where("id = ?", pun.original_board_id).first(1).each do |board| %>
                        <%= link_to (board.name), board_path(board) %>
                        <% end %>


                      </div>
                    </div>

                  </li>
                  <% end %>


                </ul>


          <!-- REPUN MODAL -->
    <% if user_signed_in? %>

    <div id="modal-<%= pun.id %>" class="modal">

            <div id="modal-share-pun">

                <div class="header">
                    Partager La Punaise
                </div>


                <%= form_for(Pun.new(params[:pun])) do |f| %>
                <div class="formsblock">
                    
                    <div class="left">


                        <div class="field">
                            <div class="label">
                                Description:
                            </div>

                            <div class="input">
                                <%= f.text_area :description, :value => pun.description %>
                            </div>
                        </div>



                        <div class="field">
                            <div class="label">
                                Sur Quel Tableau Va Votre Punaise:
                            </div>

                            <div class="input">
                                <select id="pun_board_id" name="pun[board_id]" value="<%= pun.board_id %>">
                                    <% Board.where("user_id = ?", current_user.id).each do |board|  %>
                                        <option value="<%= board.id %>"><%= board.name %> </option>
                                    <% end %>
                                </select>
                            </div>
                        </div>


                        <div class="fieldbutton">
                            <div class="label">
                                
                            </div>

                            <div class="input">
                                <%= link_to "Ajouter un Tableau", "#modal-new-board", :rel => "modal:open" %>
                            </div>
                        </div>


                    </div>

                    <div class="right">

                        <div class="shared-pun">
                            <%= image_tag pun.image_url(:share).to_s %>
                        </div>
                            
                    </div>

                </div>



                    <%= f.hidden_field :remote_image_url, :value => "http://localhost:8080"+pun.image_url.to_s %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>


                    <% if pun.original_board_id.nil? %>
                        <%= f.hidden_field :original_board_id, :value => pun.board_id %>
                        <%= f.hidden_field :original_punaise_id, :value => pun.id %>
                        <%= f.hidden_field :original_user_id, :value => pun.user_id %>
                    <% else %>
                        <%= f.hidden_field :original_board_id, :value => pun.original_board_id %>
                        <%= f.hidden_field :original_punaise_id, :value => pun.original_punaise_id %>
                        <%= f.hidden_field :original_user_id, :value => pun.original_user_id %>
                    <% end %>

                    <%= f.hidden_field :websource, :value => pun.websource %>
                    <%= f.hidden_field :link, :value => pun.websource %>

                <div id="actions">
                    <input name="commit" type="submit" value="Clouer" />
                </div>


                              
                <% end %>


            </div>

    </div> 

    <% end %>



      </li>







        <% end %>
    </div>
</div>

  <script type="text/javascript">
    $(document).ready(new function() {
      // Prepare layout options.
      var options = {
        autoResize: true, // This will auto-update the layout when the browser window is resized.
        container: $('#tabs-1 #userpunslist'), // Optional, used for some extra CSS styling
        offset: 15, // Optional, the distance between grid items
        itemWidth: 240 // Optional, the width of a grid item
      };

      // Get a reference to your grid items.
      var handler = $('#tiles .tile');

      // Call the layout function.
      handler.wookmark(options);

      $('#tiles .tile').imagesLoaded(function() {
		  // do stuff after images are loaded
		  handler.wookmark(options);
		});


      $('#userpunslist').trigger('refreshWookmark');

    });
  </script>

app/views/users/board.html.erb
<p id="notice"><%= notice %></p>


<div id="ubox">
  <div class="left">
    <div class="avatar">
      <%= image_tag @user.avatar_url(:profil).to_s %>
    </div>

    <div class="credits">
      <div class="name">
        <%= @user.username %>
      </div>
      
    </div>

    <div class="downlinks">
    <% if user_signed_in? %>
      <% if (@user.id == current_user.id) %>
      <%= link_to (image_tag "icons/edit.png"), edit_user_path(current_user) %>
      <% end %>
    <% end %>
    </div>
  </div>

  <div class="right">
    
  </div>
</div>

<div id="uinfobar">
  <div class="punaisescount">
    <a href="#" ><%= Pun.where("user_id = ?", @user.id).count %> Punaises</a>
  </div>
</div>

<!--
<%= render "users/user_puns_list" %>
-->

<%= render "users/user_boards_list" %>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<div id="usettings">
	
	<%= form_for(@user) do |f| %>
	
	<h1>Parametres du Compte</h1>
	
	<div class="form">

		<div class="title">
			Informations de base
		</div>


		  <div class="field">
		    <div class="label">
		    	Nom:
		    </div>
		    <div class="champ">
		    	<%= f.text_field :username %>
		    </div>
		  </div>


		  <div class="field">
		    <div class="label">
		    	Email:
		    </div>
		    <div class="champ">
		    	<%= f.text_field :email %>
		    </div>
		  </div>


		  <div class="field">
		    <div class="label">
		    	Avatar:
		    </div>
		    <div class="champ">
		    <%= f.file_field :avatar %>
		    </div>
		  </div>


		  <div class="field">
		    <div class="label">
		    	Pays:
		    </div>
		    <div class="champ">
		    	<select id="user_country_id" name="user[country_id]">
			      <% Country.all.each do |country|  %>
			        <option value="<%= country.id %>"><%= country.name %> </option>
			      <% end %>
			    </select>
		  	</div>
		  </div>


		  <div class="field">
		    <div class="label">
		    	Ville:
		    </div>
		    <div class="champ">
		    	<select id="user_state_id" name="user[state_id]">
			      <% State.all.each do |state|  %>
			        <option value="<%= state.id %>"><%= state.name %> </option>
			      <% end %>
			    </select>
		  	</div>
		  </div>

		</div>

		<div class="submitbox">
			<div class="nuclear">
				<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>

			<div class="actions">
				<a href="">Cancel</a>
				<%= f.submit %>
			</div>
		</div>
		  

		
	</div>

	<% end %>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Avatar</th>
    <th>Slug</th>
    <th>Country</th>
    <th>State</th>
    <th>Is admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.avatar %></td>
    <td><%= user.slug %></td>
    <td><%= user.country_id %></td>
    <td><%= user.state_id %></td>
    <td><%= user.is_admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/settings.html.erb
<div id="usettings">
	
	<%= form_for(@user) do |f| %>
	
	<h1>Parametres du Compte</h1>
	
	<div class="form">

		<div class="title">
			Informations de base
		</div>


		  <div class="field">
		    <div class="label">
		    	Nom:
		    </div>
		    <div class="champ">
		    	<%= f.text_field :username %>
		    </div>
		  </div>


		  <div class="field">
		    <div class="label">
		    	Email:
		    </div>
		    <div class="champ">
		    	<%= f.text_field :email %>
		    </div>
		  </div>


		  <div class="field">
		    <div class="label">
		    	Avatar:
		    </div>
		    <div class="champ">
		    <%= f.file_field :avatar %>
		    </div>
		  </div>


		  <div class="field">
		    <%= f.label :country_id %><br />
		    <%= f.number_field :country_id %>
		  </div>
		  <div class="field">
		    <%= f.label :state_id %><br />
		    <%= f.number_field :state_id %>
		  </div>

		</div>

		<div class="submitbox">
			<div class="nuclear">
				<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>

			<div class="actions">
				<a href="">Cancel</a>
				<%= f.submit %>
			</div>
		</div>
		  

		
	</div>

	<% end %>
</div>

app/views/users/show.html.erb
<div id="ubox">
  <div class="left">
    <div class="avatar">
      <%= image_tag @user.avatar_url(:profil).to_s %>
    </div>

    <div class="credits">
      <div class="name">
        <%= @user.username %>
      </div>
      
    </div>

    <div class="downlinks">
    <% if user_signed_in? and (@user.id == current_user.id) %>
      <%= link_to (image_tag "icons/edit.png"), edit_user_path(current_user) %>
    <% end %>
    </div>
  </div>

  <div class="right">
    <% if user_signed_in? and (@user.id != current_user.id) %>
    <%= form_for "/users/follow/" do |f| %>
      <%= submit_tag (current_user.follows?(@user) ? "Following" : "Not following"), :class => "button" %>
    <% end %>
    <% end %>
  </div>
</div>

<div id="sectoreduserdata">
  
<div id="uinfobar">
  <ul>
    <li><a href="#tabs-1"><%= Pun.where("user_id = ?", @user.id).count %> Punaises</a></li>
    <li><a href="#tabs-2"><%= Board.where("user_id = ?", @user.id).count %> Tableaux</a></li>
  </ul>

</div>

  <div id="tabs-1">
    <%= render "users/user_puns_list" %>
  </div>
  <div id="tabs-2">
    <%= render "users/user_boards_list" %>
  </div>

</div>