config/routes.rb
Punaise::Application.routes.draw do
  resources :currencies

  resources :boards

  resources :comments

  resources :puns

  resources :homes

  resources :states

  resources :countries

  devise_for :users

  resources :categories

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end
  
  resources :users

resources :puns, :only => [:index, :show] do
  resources :likes, :only => [:create, :destroy]
end

  get "users/:id/board" => "users#board"
  

  match '/:id/toggle_like', to: 'puns#toggle_like', as: 'toggle_like'
  match '/:id/toggle_follow', to: 'boards#toggle_follow', as: 'toggle_follow'

  root :to => 'homes#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :cover_id, :name, :description, :user_id, :slug

  acts_as_followable


  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user

  has_many :puns
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :approved, :content, :pun_id, :user_id

  belongs_to :user
  belongs_to :pun
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :continent_id, :flag, :name, :slug
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :is_enabled, :name, :symbol

  has_many :puns
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/pun.rb
class Pun < ActiveRecord::Base
  attr_accessible :board_id, :category_id, :image, :remote_image_url, :slug, :link, :description, :is_deleted, :original_board_id, :original_punaise_id, :original_user_id, :user_id, :price, :is_product, :currency_id, :websource

  extend FriendlyId
  friendly_id :description, use: :slugged

  acts_as_likeable

  mount_uploader :image, ImageUploader

  has_many :comments

  belongs_to :user
  belongs_to :board
  belongs_to :currency
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :country_id, :is_admin, :username, :slug, :state_id

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :username, use: :slugged

  acts_as_liker
  acts_as_follower
  acts_as_followable

  has_many :puns

  has_many :comments
  
end

app/controllers/puns_controller.rb
class PunsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :update, :destroy, :edit]
  # GET /puns
  # GET /puns.json
  def index
    @puns = Pun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @puns }
    end
  end

  # GET /puns/1
  # GET /puns/1.json
  def show
    @pun = Pun.find(params[:id])
    @board = @pun.board

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pun }
    end
  end

  # GET /puns/new
  # GET /puns/new.json
  def new
    @pun = Pun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pun }
    end
  end

  # GET /puns/1/edit
  def edit
    @pun = Pun.find(params[:id])
  end

  # GET /puns/1/edit
  def toggle_like
    @pun = Pun.find(params[:id])
    current_user.toggle_like!(@pun)
    #redirect_to pun_path(@pun)
    respond_to do |format|
      format.js { render :action => 'toggle_like' }
    end
  end

  # POST /puns
  # POST /puns.json
  def create
    @pun = Pun.new(params[:pun])

    respond_to do |format|
      if @pun.save
        format.html { redirect_to @pun, notice: 'Pun was successfully created.' }
        #format.json { render :action => 'bgajax/prepend', location: @pun }
      else
        format.html { render action: "new" }
        format.json { render json: @pun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /puns/1
  # PUT /puns/1.json
  def update
    @pun = Pun.find(params[:id])

    respond_to do |format|
      if @pun.update_attributes(params[:pun])
        format.html { redirect_to @pun, notice: 'Pun was successfully updated.' }

        #format.js { render :action => 'edit_pun' }

      else
        format.html { render action: "edit" }
        format.json { render json: @pun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puns/1
  # DELETE /puns/1.json
  def destroy
    @pun = Pun.find(params[:id])
    @pun.destroy

    respond_to do |format|
      format.html { redirect_to puns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/puns_helper.rb
module PunsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/puns/_form.html.erb
<%= form_for(@pun) do |f| %>


  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <%= f.text_field :remote_image_url %>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :original_user_id %><br />
    <%= f.hidden_field :original_user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br />
    <%= f.number_field :board_id %>
  </div>
  <div class="field">
    <%= f.label :original_board_id %><br />
    <%= f.number_field :original_board_id %>
  </div>
  <div class="field">
    <%= f.label :original_punaise_id %><br />
    <%= f.number_field :original_punaise_id %>
  </div>
  <div class="field">
    <%= f.label :websource %><br />
    <%= f.text_field :websource %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :is_product %><br />
    <%= f.check_box :is_product %>
  </div>
  <div class="field">
    Dans :<br />
    <select id="pun_currency_id" name="pun[currency_id]">
      <% Currency.order("name ASC").each do |currency|  %>
        <option value="<%= currency.id %>"><%= currency.name %> </option>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puns/_panel.html.erb
<% if user_signed_in? %>
	<%= link_to "Ajouter à mon Tableau", "#modal-" + @pun.id.to_s, :class => "weblink", :rel => "modal:open" %>

	<% if current_user.likes?(@pun) %>
	    <%= link_to "Je n'aime plus", toggle_like_path(@pun), :remote => true, :class => "weblink" %>
	<% else %>
	    <%= link_to "J'aime", toggle_like_path(@pun), :remote => true, :class => "weblink" %>
	<% end %>

<% end %>

<% unless @pun.link.nil? %>
	<%= link_to "Site Web", "http://" + @pun.link, :class => "weblink" %>
<% end %>

<% if user_signed_in? and (@pun.user_id == current_user.id) %>

	<%= link_to "Modifier", "#modal-edit-" + @pun.id.to_s, :class => "weblink", :rel => "modal:open" %>

<% end %>

app/views/puns/_pun.html.erb
      <li class="tile">

                <!-- La Punaise Elle meme -->
                <div class="lapunaise">

                  <%= link_to (image_tag pun.image_url(:grid).to_s), pun_path(pun) %>

                  <div id="pun-like-links">
                    <div class="top-link" id="punscount-<%= pun.id %>"><a href="#modal-<%= pun.id %>"><%= Pun.where("original_punaise_id = ?", pun.original_punaise_id).count + 1 %> <%= image_tag "icon/punaise2.png" %></a></div>
                    <div class="top-link" id="likescount-<%= pun.id %>"> <%= link_to pun.likers(User).count.to_s, toggle_like_path(pun), :remote => true %><%= link_to (image_tag "icon/love2.png"), toggle_like_path(pun), :remote => true %></div>
                  </div>

                </div>

                <!-- La description -->
                <% unless pun.description.nil? %>
                <div class="description">
                  <%= pun.description %>
                </div>
                <% end %>

                <ul class="pundatas">
                  <li class="pundata" %>
                    <div class="thumb">
                      <%= image_tag pun.user.avatar_url(:pundatathumb).to_s %>
                    </div>

                    <div class="data">
                      <div class="by">
                        par
                      </div>
                      <div class="user">
                        <%= link_to pun.user.username, user_path(pun.user) %>
                      </div>
                    </div>
                  </li>
                  

                  <!-- PUNNED ON -->
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.board_id).first(1).each do |boardthumb| %>
                        <%= link_to (image_tag boardthumb.image_url(:boardthumb).to_s), board_path(boardthumb.board) %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Clouée sur
                      </div>
                      <div class="board">

                        <%= link_to (pun.board.name), board_path(pun.board) %>


                      </div>
                    </div>

                  </li>

                  

                  <!-- ORIGINALLY PUNNED ON -->
                  <% unless pun.original_board_id.nil? %>
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.original_board_id).first(1).each do |boardthumb| %>
                        <%= link_to (image_tag boardthumb.image_url(:boardthumb).to_s), board_path(boardthumb.board) %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Originellement sur
                      </div>
                      <div class="board">
                        <% Board.where("id = ?", pun.original_board_id).first(1).each do |board| %>
                        <%= link_to (board.name), board_path(board) %>
                        <% end %>


                      </div>
                    </div>

                  </li>
                  <% end %>


                </ul>


              
    <aside id="modal-<%= pun.id %>" class="modal">
        <div>

            <div id="modal-share-pun">



              <div class="forms">
                <%= form_for(Pun.new(params[:pun]), :remote => true) do |f| %>
                <div class="left">


	                <select id="pun_board_id" name="pun[board_id]">
	                    <% Board.where("user_id = ?", current_user.id).each do |board|  %>
	                        <option value="<%= board.id %>"><%= board.name %> </option>
	                    <% end %>
	                </select>

                    <%= link_to "Ajouter un Tableau", "#modal-new-board" %>

                  	<%= f.text_field :description, :value => pun.description %>

                </div>

                <div class="right">

	              	<div class="topshow">
		                <div class="shared-pun">
		                        <%= image_tag pun.image_url(:share).to_s %>
		                </div>

		                <div class="thumbs">
		                    <div class="data">
		                        Par <%= image_tag pun.user.avatar_url(:pundatathumb).to_s, :title => pun.user.username %> sur 

			                    <% Pun.where("board_id = ?", pun.board).first(1).each do |boardthumb| %>
			                        <%= image_tag boardthumb.image_url(:datathumb).to_s, :title => pun.board.name %>
			                    <% end %>
		                	</div>
		                        
		                </div>
		            </div>

                </div>

                <%= f.hidden_field :remote_image_url, :value => "http://localhost:3000"+pun.image_url.to_s %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>


                    <% if pun.original_board_id.nil? %>
                        <%= f.hidden_field :original_board_id, :value => pun.board_id %>
                        <%= f.hidden_field :original_punaise_id, :value => pun.id %>
                        <%= f.hidden_field :original_user_id, :value => pun.user_id %>
                    <% else %>
                        <%= f.hidden_field :original_board_id, :value => pun.original_board_id %>
                        <%= f.hidden_field :original_punaise_id, :value => pun.original_punaise_id %>
                        <%= f.hidden_field :original_user_id, :value => pun.original_user_id %>
                    <% end %>

                    <%= f.hidden_field :websource, :value => pun.websource %>
                    <%= f.hidden_field :link, :value => pun.websource %>
                    <%= f.hidden_field :category_id, :value => pun.category_id %>

                    <div id="actions">
                      <input name="commit" type="submit" value="Clouer" />
                    </div>

                <% end %>
              </div>
                              



                    </div>
            <a href="#close" title="Close">Close</a>
        </div>
    </aside> 

      </li>







    





  <script type="text/javascript">
    $(document).ready(new function() {
      // Prepare layout options.
      var options = {
        autoResize: true, // This will auto-update the layout when the browser window is resized.
        container: $('#tiles'), // Optional, used for some extra CSS styling
        offset: 15, // Optional, the distance between grid items
        itemWidth: 240 // Optional, the width of a grid item
      };

      // Get a reference to your grid items.
      var handler = $('#tiles .tile');

      // Call the layout function.
      handler.wookmark(options);

      $('#tiles .tile').imagesLoaded(function() {
		  // do stuff after images are loaded
		  handler.wookmark(options);
		});



      $('#punslist').trigger('refreshWookmark');

    });
  </script>

app/views/puns/_pun_stats.html.erb
    		<%= @pun.likers(User).count %> <%= image_tag "icon/love.png" %>   <%= @pun.comments.where("pun_id = ?", @pun.id).count %> <%= image_tag "icon/comment.png" %>

app/views/puns/_puns_else_where.html.erb
<h1>Également épinglé sur :</h1>

<% Pun.where("original_punaise_id = ?", @pun.id).each do |repun|  %>
      
	<div class="board">
		<div class="title">
			<%= link_to (repun.board.name), board_path(repun.board) %>
		</div>
		<div class="maincover">
			<% Pun.where("board_id = ?", repun.board.id).first(1).each do |boardmainthumb| %>
	            <%= image_tag boardmainthumb.image_url(:userboardthumb).to_s %>
	        <% end %>
		</div>
		<div class="tinycovers">

			<% Pun.where("board_id = ?", repun.board.id).last(4).each do |boardtinythumb| %>
				<div class="tinycover">
		            <%= image_tag boardtinythumb.image_url(:userboardtinythumb).to_s %>
				</div>
	        <% end %>
		</div>
		<div class="edit"><a href="">Modifier</a></div>
	</div>
<% end %>

app/views/puns/_punshow_originally_on_bloc.html.erb
<div class="originally-on-bloc">
	<div class="originally-on">
		<% Pun.where("board_id = ?", @pun.original_board_id).first(1).each do |boardthumb| %>
			<div class="thumb">
   				<%= image_tag boardthumb.image_url(:thumb).to_s %>
			</div>
			<div class="text">
				<div class="label">
					Originellement Sur
				</div>
				<div class="content">
					<%= link_to (boardthumb.board.name), board_path(boardthumb.board) %>
				</div>
			</div>
		<% end %>
	</div>

	<div class="originally-by">
		<% Pun.where("board_id = ?", @pun.original_board_id).first(1).each do |boardthumb| %>
			<div class="thumb">
   				<%= image_tag boardthumb.user.avatar_url(:commentsthumb).to_s %>
			</div>
			<div class="text">
				<div class="label">
					Par
				</div>
				<div class="content">
					<%= link_to (boardthumb.user.username), user_path(boardthumb.user) %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/puns/_punshow_product_price.html.erb
	<div class="annonce">
		Vous pourrez l'avoir pour
	</div>
	<div class="price">
		<%= @pun.price %> <%= @pun.currency.symbol %>
	</div>

app/views/puns/_punshow_right_otherpuns.html.erb
<% unless (Pun.where("user_id = ? AND original_punaise_id IS NULL", @pun.user_id).count == 0) %>
<div class="otherpuns">

    <div class="otherby">Autres punaises par</div>

    <div class="punner"><%= link_to @pun.user.username, user_path(@pun.user) %></div>

    <div class="puns">
        <% Pun.where("user_id = ? AND original_punaise_id IS NULL", @pun.user_id).last(12).each do |punthumb| %>
          <%= link_to (image_tag punthumb.image_url(:thumb).to_s, :title => punthumb.description), pun_path(punthumb) %>
        <% end %>
    </div>
    
</div>
<% end %>

app/views/puns/_repunners_puns.html.erb
<div id="repunnerspuns">
	<div id="tiles" class="repunner">
		
          <% Pun.where("original_punaise_id = ?", @pun.id).last(20).each do |pun| %>
          	
            <li class="tile">
                <div class="toplink">
                  <a href="#modal-<%= pun.id %>"><div class="punit"></div></a>
                </div>
                <%= link_to (image_tag pun.image_url(:grid).to_s), pun_path(pun) %>

                <div class="description">
                	<%= pun.description %>
                </div>

                <ul class="pundatas">
                	<li class="pundata" %>
                		<div class="thumb">
                			<%= image_tag pun.user.avatar_url(:pundatathumb).to_s %>
                		</div>

                		<div class="data">
                			<div class="by">
                				par
                			</div>
                			<div class="user">
                				<%= link_to pun.user.username, user_path(pun.user) %>
                			</div>
                		</div>
                	</li>
                  

                  <!-- PUNNED ON -->
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.board_id).first(1).each do |boardthumb| %>
                        <%= image_tag boardthumb.image_url(:boardthumb).to_s %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Clouée sur
                      </div>
                      <div class="board">

                        <%= pun.board.name %>


                      </div>
                    </div>

                  </li>

                  

                  <!-- ORIGINALLY PUNNED ON -->
                  <% unless pun.original_board_id.nil? %>
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.original_board_id).first(1).each do |boardthumb| %>
                        <%= image_tag boardthumb.image_url(:boardthumb).to_s %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Originellement sur
                      </div>
                      <div class="board">
                        <% Board.where("id = ?", pun.original_board_id).first(1).each do |board| %>
                        <%= board.name %>
                        <% end %>


                      </div>
                    </div>

                  </li>
                  <% end %>


                </ul>



              <aside id="modal-<%= pun.id %>" class="modal">


                        <div id="modal-share-pun">
                          
                          <div class="left">
                            <div class="shared-pun">
                              <%= image_tag pun.image_url(:grid).to_s %>
                            </div>

                            <div class="original-punner">
                              <div class="uthumb">
                                <%= image_tag pun.user.avatar_url(:pundatathumb).to_s %>
                              </div>

                              <div class="uname">
                                Ajoutée par <%= link_to pun.user.username, user_path(pun.user) %>
                              </div>
                            </div>
                            
                            <!-- exception a enlevé ulterieurment -->
                            <% unless pun.board.nil? %>
                            <div class="original-board">
                              <div class="boardthumb">
                                <% Pun.where("board_id = ?", pun.board).first(1).each do |boardthumb| %>
                                  <%= image_tag boardthumb.image_url(:datathumb).to_s %>
                                <% end %>
                              </div>

                              <div class="punboard">
                                  Originellement sur <%= pun.board.name %>
                              </div>
                            </div>
                            <% end %>

                          </div>

                          <div class="right">
                            
                            <%= form_for(Pun.new(params[:pun])) do |f| %>
                              

                              <div class="label" ><%= f.label :board_id %></div>
                                <select id="pun_board_id" name="pun[board_id]">
                                  <% Board.where("user_id = ?", current_user.id).each do |board|  %>
                                    <option value="<%= board.id %>"><%= board.name %> </option>
                                  <% end %>
                                </select>
                                <%= link_to "Ajouter un Tableau", new_board_path() %>

                              <div class="label" ><%= f.label :description %></div>
                                <%= f.text_field :description, :value => pun.description %>

                                <%= f.hidden_field :remote_image_url, :value => "http://localhost:3000"+pun.image_url.to_s %>
                                <%= f.hidden_field :user_id, :value => current_user.id %>


                                <% if pun.original_board_id.nil? %>
                                  <%= f.hidden_field :original_board_id, :value => pun.board_id %>
                                  <%= f.hidden_field :original_punaise_id, :value => pun.id %>
                                  <%= f.hidden_field :original_user_id, :value => pun.user_id %>
                                <% else %>
                                  <%= f.hidden_field :original_board_id, :value => pun.original_board_id %>
                                  <%= f.hidden_field :original_punaise_id, :value => pun.original_punaise_id %>
                                  <%= f.hidden_field :original_user_id, :value => pun.original_user_id %>
                                <% end %>

                                <%= f.hidden_field :websource, :value => pun.websource %>
                                <%= f.hidden_field :link, :value => pun.websource %>


                                <div class="actions">
                                  <input name="commit" type="submit" value="Repondre" />
                                </div>

                              <% end %>

                          </div>

                        </div>



              </aside>

            </li>
        <% end %>

    </div>

</div>



<script type="text/javascript">
    $(document).ready(new function() {
      // Prepare layout options.
      var options = {
        autoResize: true, // This will auto-update the layout when the browser window is resized.
        container: $('#repunnerspuns'), // Optional, used for some extra CSS styling
        offset: 10, // Optional, the distance between grid items
        itemWidth: 235 // Optional, the width of a grid item
      };

      // Get a reference to your grid items.
      var handler = $('.tile');

      // Call the layout function.
      handler.wookmark(options);

      $('.tile').imagesLoaded(function() {
		  // do stuff after images are loaded
		  handler.wookmark(options);
		});



      $('#repunnerspuns').trigger('refreshWookmark');

    });
</script>

app/views/puns/ajax/_board_list.html.erb
                    <select id="pun_board_id" name="pun[board_id]" value="1">
                      	<% Board.order("name ASC").each do |board|  %>
                        <option value="<%= board.id %>"><%= board.name %> </option>
                      	<% end %>
                    </select>

app/views/puns/ajax/_pun_description.html.erb
<%= @pun.description %>

app/views/puns/ajax/_toggle_follow.html.erb
      <% if current_user.follows?(@board) %>
        <%= link_to "Se Désabonner", toggle_follow_path(@board), :remote => true, :class => "weblink" %>
      <% else %>
        <%= link_to "S'abonner", toggle_follow_path(@board), :remote => true, :class => "weblink" %>
      <% end %>

app/views/puns/bgajax/prepend.js.erb
$("#tiles").prepend('<%= j render(@puns) %>');

app/views/puns/comment.js.erb
$('#commentaires .commentsbloc').html('<%= escape_javascript(render :partial => "puns/punshow_comment_bloc", :locals => {:pun => @pun}) %>');

$('.punbox .pun-stats').html('<%= escape_javascript(render :partial => "puns/pun_stats", :locals => {:pun => @pun}) %>');

$('#comment_content').val('');

app/views/puns/edit_pun.js.erb
alert("tnekna");
$('#header-description').html('<%= escape_javascript(render :partial => "puns/ajax/pun_description", :locals => {:pun => @pun}) %>');

$('.product').html('<%= escape_javascript(render :partial => "puns/punshow_product_price", :locals => {:pun => @pun}) %>');

$('.boardbloc').html('<%= escape_javascript(render :partial => "puns/punshow_right_grid", :locals => {:pun => @pun}) %>');

app/views/puns/toggle_follow.js.erb
// punaise show
$('.boardbloc .follow').html('<%= escape_javascript(render :partial => "puns/ajax/toggle_follow", :locals => {:board => @board}) %>');

app/views/puns/toggle_like.js.erb
// The Punaise Page
$('.punbox .panel').html('<%= escape_javascript(render :partial => "puns/panel", :locals => {:pun => @pun}) %>');
$('.punbox .pun-stats').html('<%= escape_javascript(render :partial => "puns/pun_stats", :locals => {:pun => @pun}) %>');

// Tiles
$('#pun-like-links #likescount-<%= @pun.id %>').html('<%= escape_javascript(render :partial => "homes/toplinks/likes_count", :locals => {:pun => @pun}) %>');