config/routes.rb
Punaise::Application.routes.draw do
  resources :currencies

  resources :boards

  resources :comments

  resources :puns

  resources :homes

  resources :states

  resources :countries

  devise_for :users

  resources :categories

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end
  
  resources :users

resources :puns, :only => [:index, :show] do
  resources :likes, :only => [:create, :destroy]
end

  get "users/:id/board" => "users#board"
  

  match '/:id/toggle_like', to: 'puns#toggle_like', as: 'toggle_like'
  match '/:id/toggle_follow', to: 'boards#toggle_follow', as: 'toggle_follow'

  root :to => 'homes#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :cover_id, :name, :description, :user_id, :slug

  acts_as_followable


  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user

  has_many :puns
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :name, :slug

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :approved, :content, :pun_id, :user_id

  belongs_to :user
  belongs_to :pun
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :continent_id, :flag, :name, :slug
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :is_enabled, :name, :symbol

  has_many :puns
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/pun.rb
class Pun < ActiveRecord::Base
  attr_accessible :board_id, :category_id, :image, :remote_image_url, :slug, :link, :description, :is_deleted, :original_board_id, :original_punaise_id, :original_user_id, :user_id, :price, :is_product, :currency_id, :websource

  extend FriendlyId
  friendly_id :description, use: :slugged

  acts_as_likeable

  mount_uploader :image, ImageUploader

  has_many :comments

  belongs_to :user
  belongs_to :board
  belongs_to :currency
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :country_id, :is_admin, :username, :slug, :state_id

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :username, use: :slugged

  acts_as_liker
  acts_as_follower
  acts_as_followable

  has_many :puns

  has_many :comments
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @puns = Pun.where("category_id = ?", @category.id).order("created_at DESC").page(params[:page]).per_page(10)

    respond_to do |format|
      format.html # show.html.erb
      format.js { render :action => 'more' }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/puns_helper.rb
module PunsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.slug %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/more.js.erb
$("#tiles").append('<%= j render(@puns) %>');
<% if @puns.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@puns) %>');
<% else %>
	$('.pagination').remove();
<% end %>
<% sleep 2 %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="header-title">
	<%= @category.name %>
</div>

<div id="punslist">
    
  <div id="tiles">
    <% @puns.each do |pun| %>

      <li class="tile">



                <!-- La Punaise Elle meme -->
                <div class="lapunaise">

                  <%= link_to (image_tag pun.image_url(:grid).to_s), pun_path(pun) %>

                  <div id="pun-like-links">
                    <div class="top-link" id="punscount-<%= pun.id %>"><a id="modal-<%= pun.id %>" href="#"><%= Pun.where("original_punaise_id = ?", pun.original_punaise_id).count + 1 %> <%= image_tag "icon/punaise2.png" %></a></div>
                    <div class="top-link" id="likescount-<%= pun.id %>"> <%= link_to pun.likers(User).count.to_s, toggle_like_path(pun), :remote => true %><%= link_to (image_tag "icon/love2.png"), toggle_like_path(pun), :remote => true %></div>
                  </div>

                </div>

                <!-- La description -->
                <% unless pun.description.nil? %>
                <div class="description">
                  <%= pun.description %>
                </div>
                <% end %>

                <ul class="pundatas">
                  <li class="pundata" %>
                    <div class="thumb">
                      <%= image_tag pun.user.avatar_url(:pundatathumb).to_s %>
                    </div>

                    <div class="data">
                      <div class="by">
                        par
                      </div>
                      <div class="user">
                        <%= link_to pun.user.username, user_path(pun.user) %>
                      </div>
                    </div>
                  </li>
                  

                  <!-- PUNNED ON -->
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.board_id).first(1).each do |boardthumb| %>
                        <%= link_to (image_tag boardthumb.image_url(:boardthumb).to_s), board_path(boardthumb.board) %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Clouée sur
                      </div>
                      <div class="board">

                        <%= link_to (pun.board.name), board_path(pun.board) %>


                      </div>
                    </div>

                  </li>

                  

                  <!-- ORIGINALLY PUNNED ON -->
                  <% unless pun.original_board_id.nil? %>
                  <li class="punboard">
                    <div class="boardthumb">
                      <% Pun.where("board_id = ?", pun.original_board_id).first(1).each do |boardthumb| %>
                        <%= link_to (image_tag boardthumb.image_url(:boardthumb).to_s), board_path(boardthumb.board) %>
                      <% end %>
                    </div>

                    <div class="punnedondata">
                      <div class="punnedon">
                        Originellement sur
                      </div>
                      <div class="board">
                        <% Board.where("id = ?", pun.original_board_id).first(1).each do |board| %>
                        <%= link_to (board.name), board_path(board) %>
                        <% end %>


                      </div>
                    </div>

                  </li>
                  <% end %>


                </ul>


              
    <div id="modal-<%= pun.id %>" class="modal">
        <div>

            <div id="modal-share-pun">



              <div class="forms">
                <%= form_for(Pun.new(params[:pun]), :remote => true) do |f| %>
                <div class="left">

                  <div class="field">
                    <div class="label">
                      Tableau
                    </div>
                    <div class="input">
                      <select id="pun_board_id" name="pun[board_id]">
                          <% Board.where("user_id = ?", current_user.id).each do |board|  %>
                              <option value="<%= board.id %>"><%= board.name %> </option>
                          <% end %>
                      </select>                    
                    </div>                    
                  </div>




                  <div class="field">
                    
                    <div class="label">
                      Description
                    </div>
                    <div class="input">
                      <%= f.text_area :description, :value => pun.description %>
                    </div>

                  </div>


                  <div class="field">
                    
                    <div class="label">
                      
                    </div>
                    <div class="input">
                      <%= link_to "Ajouter un Tableau", "#modal-new-board" %>
                    </div>

                  </div>

                   

                    

                </div>

                <div class="right">

                  <div class="rightshow">
                    <div class="shared-pun">
                            <%= image_tag pun.image_url(:share).to_s %>
                    </div>

                  </div>

                </div>

                <%= f.hidden_field :remote_image_url, :value => "http://localhost:3000"+pun.image_url.to_s %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>


                    <% if pun.original_board_id.nil? %>
                        <%= f.hidden_field :original_board_id, :value => pun.board_id %>
                        <%= f.hidden_field :original_punaise_id, :value => pun.id %>
                        <%= f.hidden_field :original_user_id, :value => pun.user_id %>
                    <% else %>
                        <%= f.hidden_field :original_board_id, :value => pun.original_board_id %>
                        <%= f.hidden_field :original_punaise_id, :value => pun.original_punaise_id %>
                        <%= f.hidden_field :original_user_id, :value => pun.original_user_id %>
                    <% end %>

                    <%= f.hidden_field :websource, :value => pun.websource %>
                    <%= f.hidden_field :link, :value => pun.websource %>
                    <%= f.hidden_field :category_id, :value => pun.category_id %>

                    <div id="actions">
                      <input name="commit" type="submit" value="Clouer" />
                    </div>

                <% end %>
              </div>
                              



                    </div>
            <a href="#close" title="Close">Close</a>
        </div>
    </div> 

      </li>


        <% end %>
    </div>
</div>


<%= will_paginate(@puns) %>



  <script type="text/javascript">
    $(document).ready(new function() {
      // Prepare layout options.
      var options = {
        autoResize: true, // This will auto-update the layout when the browser window is resized.
        container: $('#punslist'), // Optional, used for some extra CSS styling
        offset: 10, // Optional, the distance between grid items
        itemWidth: 235 // Optional, the width of a grid item
      };

      // Get a reference to your grid items.
      var handler = $('#tiles .tile');

      // Call the layout function.
      handler.wookmark(options);

      $('#tiles .tile').imagesLoaded(function() {
		  // do stuff after images are loaded
		  handler.wookmark(options);
		});



      $('#punslist').trigger('refreshWookmark');

    });
  </script>